### ISSUE TITLE
Section 7.4.2. Statistician Responsibility (wording)

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#103]
The second bullet reads:
>    Be responsible for keeping individual teams' scores

Suggested reading:

> Be responsible for keeping team scores

**Comment by jttower** [comment]
I agree the suggested wording is more clear. (Unless someone can give an example of why it isn't?)

**Comment by ARMediting** [comment]
It's not really necessary in either bullet point.

**Comment by jttower** [comment]
Rules Committee voted on 3/20/22 for this change:
"Be responsible for keeping team scores"
Vote passed 6-0.
On behalf of the Rules Committee, this issue is closed.
