### ISSUE TITLE
Leftovers

### ISSUE THREAD

**Issue by gryphonshafer** [gryphonshafer/Quizzing-Rule-Book#110]
The following are "leftovers" from the v1 project that should be reviewed for possible inclusion in either best practices or elsewhere (or deleting):

# Leftovers

Content that exists in the current rule book that does not fit anywhere in the migrated rule book.

## International Head Coach

The international coach must be approved by their district office/committee or by the District Bible Quizzing Coordinator.

## District Coordinator

The district quizmaster and officials will be approved by the District Bible Quizzing Coordinator or Committee.

## Competitive Levels

There are 4 levels of Bible quiz competition: local or interchurch, zone, district, and International Finals. Each district shall determine eligibility guidelines for all local, zone, and district competitions subject to approval by the district office.

### Local or Interchurch Quizzing

- (Within a church or between several churches on an unofficial basis) Any number from 1 to 5 may constitute a team.
- Any number of teams may participate.
- The person/people responsible for preparation of the quizzes used for competition will be assigned by the person in charge of sponsoring the competition.
- If a church is unable to secure enough teens for study and competition within its own group, it may work with a neighboring church for competition on this level.
- Follow all other rules as clearly as possible in order to educate for zone and higher levels of competition.

### Zone Quizzing

- The quizmaster and officials will be selected by the Zone/District Executive Committee/District Coordinator, or Designee.
- The person/people responsible for preparation of the quizzes used for competition will be assigned by the District Coordinator or Zone Coordinator.
- Follow rules as determined by district for zone quiz meets.

### District Quizzing

- Rules may be modified by each district to suit the needs of their district. Any changes in the rules need to be approved by the District Coordinator or District Committee. The district office may grant exemptions for unusual circumstances in regard to district quizzing only.
- The quizmaster and officials will be approved by the District Committee or District Coordinator.
- The name and address of the district coordinator must be sent to the Life Impact Office by October 1st of that quiz season.
- For district finals, each quiz must cover the season's material in its entirety.

#### Preliminary Round Brackets

The following are pairings for preliminary round quizzing with 3 quizzes per team. (In quizzes with 4 to 6 teams, some teams compete with each other twice.)

4 teams

1. ABC
2. DAB
3. CDA
4. BCD

5 teams

1. ABC
2. DEA
3. BCD
4. EAB
5. CDE

6 teams

1. ACF
2. BDA
3. CEB
4. DFC
5. EAD
6. FBE

7 teams

1. ACG
2. BDA
3. CEB
4. DFC
5. EGD
6. FAE
7. GBF

8 teams

1. ABC
2. DEF
3. GHA
4. GCE
5. ADF
6. BEH
7. FHC
8. GBD

9 Teams

1. ABC
2. DEF
3. GHI
4. ADG
5. BEH
6. CDH
7. AEI
8. BFG
9. CFI

10 Teams

1. ABC
2. DEF
3. GHI
4. JBF
5. ADG
6. BEH
7. CFI
8. JEG
9. CDH
10. IJA

11 Teams

1. ABJ
2. BCK
3. CDA
4. DEB
5. EFC
6. FGD
7. GHE
8. HIF
9. IJG
10. JKH
11. KAI

12 Teams

1. ABK
2. CFE
3. GIJ
4. EDB
5. FHI
6. AJL
7. EGH
8. ACD
9. KJH
10. LCB
11. DFG
12. ILK

13 Teams

1. CFG
2. IHE
3. GJK
4. LIM
5. BKA
6. DMC
7. BEF
8. HGD
9. FJI
10. KLH
11. AJM
12. CBL
13. DAE

14 Teams

1. ADE
2. CFG
3. EHI
4. ILM
5. GJK
6. KNA
7. BMC
8. LKH
9. FIJ
10. DHG
11. BEF
12. JMN
13. ABL
14. NCD

15 Teams

1. BEF
2. GJK
3. EDA
4. DCO
5. NBC
6. ALO
7. CFG
8. FIJ
9. IML
10. HGD
11. MJN
12. LKH
13. ABM
14. IHE
15. ONK

16 Teams

1. CFG
2. ADE
3. DGH
4. LOP
5. EBF
6. KON
7. PDC
8. HEI
9. HKL
10. BCO
11. FIJ
12. NAB
13. ILM
14. GJK
15. JMN
16. MPA

17 Teams

1. CDL
2. EGO
3. HFM
4. KIP
5. NJQ
6. FAL
7. BMG
8. DOI
9. HCN
10. EKQ
11. JPB
12. MNO
13. DEF
14. ABC
15. GHI
16. JLK
17. PQA

18 Teams

1. AJR
2. BPK
3. FIM
4. DGN
5. CLQ
6. EOH
7. GMA
8. JDP
9. HBN
10. ICO
11. KEQ
12. LRF
13. BAC
14. DFE
15. GHI
16. JKL
17. MNO
18. PQR

19 Teams

1. IOS
2. HFN
3. LCP
4. EGM
5. AJQ
6. KRD
7. CIN
8. BMH
9. FLQ
10. JDO
11. EPK
12. RSB
13. GHI
14. DEF
15. ABC
16. JKL
17. MNO
18. PQR
19. SAG

20 Teams

1. HSO
2. TGP
3. CJM
4. NFQ
5. BIR
6. ELS
7. KDT
8. HCN
9. JPB
10. FAL
11. DOI
12. EQK
13. RMG
14. ABC
15. DEF
16. GHI
17. JKL
18. MNO
19. PRQ
20. STA

21 Teams

1. DAG
2. JMP
3. BHE
4. KNQ
5. LRO
6. CFI
7. SPA
8. HUR
9. TLQ
10. MDI
11. SCJ
12. FKU
13. ETN
14. OGB
15. PQR
16. TSU
17. DEF
18. ABC
19. GIH
20. KJL
21. MON

**Comment by jswingle** [comment]
I'll go through the points in orde, but the tl;dr version is **all of these should just be removed from the rulebook.**

@gryphonshafer @scottpeterson @ZacharyTinker Your comments appreciated.

**International Head Coach**
Obviously a team that represents a specific district is going to be collaborating in some way with the quiz program there, including whoever coordinates it. But I'm not opposed to a team coming to IBQ that is separate from a district, if the desire to come is there. I see no reason to put the rule back in the book.

**District Coordinator**
Obviously this will be the case, unnecessary rule. It basically just says "the person who's in charge, is in charge"

**Competitive Levels**
The distinctions between local/interchurch/zone quizzing were never, in my experience, considered or used as a concept anywhere except in the rulebook. So this should stay out of the rulebook.

**District**

- Rules may be modified by each district to suit the needs of their district. Any changes in the rules need to be approved by the District Coordinator or District Committee. The district office may grant exemptions for unusual circumstances in regard to district quizzing only.

This bullet point is good and should stay in the rulebook, but it's already in the current version by another phrasing in the very first paragraph of the rulebook: "This is the official rule book for Bible Quizzing, which represents what will be followed at the annual International Bible Quizzing (IBQ) championship meet at the end of a quiz season. It is also a recommendational document for Quizzing districts and any other organizations interested in Bible Quizzing. These districts and other organizations retain the right to set and enforce their own rules using whatever mechanisms they deem most appropriate."

The other bullet points are either deprecated or unnecessary. It's not really the rulebook's job to mandate what material is used in a district finals, for example.

**Brackets**

I think we already have tickets open on the issue of brackets. I don't think the rulebook needs to specify preliminary brackets, so this can stay out of the current rulebook.

**Comment by ARMediting** [comment]
I can imagine some best practices or "how to start a quiz program" document that discusses local, zone, district, and internationals distinctions, especially since zone is less known and used but can be helpful. But since the rulebook states that it only truly applies to Internationals, I'm fine with keeping this out. And bracket pairings is a nice help for leaders, but surely you could find similar lists by googling?

**Comment by ARMediting** [comment]
On behalf of the Rules Committee:

During our meeting on 9/12/2022, the Rules Committee voted 5-0 to close the issue with no further action.

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md

We did bring up the value of some of these leftover items, potentially in a best practices or introduction to quizzing document, but they don't need an issue here.
