### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by gryphonshafer** [gryphonshafer/Quizzing-Rule-Book#112]
I think we can (and therefore should) provide a download version option that has a generated table of contents that appears after the first section. It couldn't include page numbers, but it could include internal links.

**Comment by jttower** [comment]
Agreed.  I actually created my own table of contents, as I think it makes using the Rule Book much easier.

**Comment by ARMediting** [comment]
Also, I'm not sure where to ask about this, but is there a version of the PDF that's searchable? I haven't found one yet.

**Comment by scottpeterson** [comment]
It's searchable for me.

**Comment by jswingle** [comment]
I just use the HTML render for searching.

**Comment by jswingle** [comment]
https://github.com/gryphonshafer/Quizzing-Rule-Book/releases/latest/download/rule_book_full.html

**Comment by scottpeterson** [comment]
Sure, but the PDF versions should also be searchable.

**Comment by gryphonshafer** [comment]
PDFs are searchable for me. What PDF viewer (and version) do you use?

**Comment by scottpeterson** [comment]
(In Preview, Firefox, or Chrome, on macOS)

**Comment by gryphonshafer** [comment]
What versions thereof? Have you tried a viewer from Adobe?

**Comment by ARMediting** [comment]
Standard Adobe Acrobat reader

**Comment by gryphonshafer** [comment]
The work for this ticket is done. PDF and "paged" HTML renders have page numbers, table of contents (with internal links), and (as an early Christmas present for Zach) a cover page. I've built the functionality as a separate GitHub Action available in the Marketplace that can be integrated into this project (when the time right). Here's a preview:

https://github.com/gryphonshafer/test-book

Integration will involve ripping out all the existing code here (not content), adding a reference and settings to the Action, and then some minor technical-only edits to the content. Therefore, I think it's best to consider performing this work immediately after the `integration` branch is merged with `master`.

**Comment by jswingle** [comment]
I like the ToC. Since this is not a substantive rule change but rather a formatting addition I don't think we need to undergo the typical 3-month process that PRs usually go through. I'm happy to just kick it to one RC vote.

Also, I seem to be able to search the PDF on the test-book branch but still can't on the master. Did you change anything else, @gryphonshafer?

**Comment by jswingle** [comment]
On behalf of the Rules Committee:

During our meeting on 9/12/2022, the Rules Committee voted 5-0 to close this issue. This means we've examined the discussion and decided that nothing ought to be changed at this time.

We approved of Gryphon's work on the ToC, but there is no actionable change on the rules itself, so we are closing the issue out and I personally will work with Gryphon to ensure the tech side of this is implemented.

Please note that the closing of an issue doesn't mean the issue cannot be raised again in the future.

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md
