### ISSUE TITLE
1.2.2.5. SIT (SIT) heading

### ISSUE THREAD

**Issue by kclimenhaga** [gryphonshafer/Quizzing-Rule-Book#115]
I propose that we change the wording to "1.2.2.5. Situation (SIT)" to be consistent with the other question type headings.

**Comment by scottpeterson** [comment]
Agreed.  

Current is "1.2.2.5. SIT (SIT)"   ( I had to look it up to see why it was inconsistent  )

**Comment by kclimenhaga** [comment]
Rules Committee voted unanimously 10/04 to change the heading to "1.2.2.5. Situation".

On behalf of the Rules Committee, this issue is closed.

**Comment by jswingle** [comment]
Looks like this issue wasn't actually technically closed back on 4/28, so I'm closing it now.
