### ISSUE TITLE
4.2.1. Context Application

### ISSUE THREAD

**Issue by jttower** [gryphonshafer/Quizzing-Rule-Book#116]
In response to Issue [#109 ](https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/109), if it is decided that the unique word rule is removed, then we need to also amend 4.2.1. Context Application:
"On all question types, a quizzer cannot automatically be ruled out of context by a single word, even if it is a unique word..." 

Therefore, if we strike the unique word rule, I think this rule would also need to be amended to remove "even if it is a unique word."

**Comment by JoshJetto** [comment]
Agreed.

**Comment by jswingle** [comment]
I would say it needs to stay.

A quizzer no longer being requred to say a unique word to be counted correct wouldn't automatically mean a misplaced unique word _couldn't_ take a quizzer out of context. These are related, but distinct, issues.

Side note, I think we can probably reword this whole rule to be clearer. @jttower and I were both part of a protest concerning this rule in Ohio last year, and it was all about the interpretation of the word "automatically." Both sides raised valid points, I think, which revealed to me that this rule is a bit ambiguous.

**Comment by jswingle** [comment]
Looks like I had a chance right away. Here's the new issue: https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/120

**Comment by jswingle** [comment]
@jttower What do you think about merging this issue with #120 ? Since it concerns the same rule and it sounds like we may be interested in making a change to the whole rule.

**Comment by jttower** [comment]
Yes, I think it is all related.  This issue is only an issue IF the rule is changed.

**Comment by jswingle** [comment]
Closing this issue out to merge it with #38 .
