### ISSUE TITLE
README.md "Referfence"

### ISSUE THREAD

**Issue by gryphonshafer** [gryphonshafer/Quizzing-Rule-Book#117]
In the main `README.md` under Reference Render, all three links say "Referfence" with an extra F.

This is of course trivial to fix, but I didn't want to autocratically fix this while the RC is just getting underway in their process because it would result in an automatic build of a new rule book version. Not a big deal, really. But I figured better for me to file this issue, and then the RC can assign it to me to work on.

**Comment by gryphonshafer** [comment]
Oh, and a thank you to Jessica Tower for spotting this bug.

**Comment by kclimenhaga** [comment]
100% agree!

**Comment by JoshJetto** [comment]
Agreed.

**Comment by jttower** [comment]
Go for it!
