### ISSUE TITLE
1st 5 Words of the Question confusion

### ISSUE THREAD

**Issue by ARMediting** [gryphonshafer/Quizzing-Rule-Book#118]
Under 1., "Material and Questions," the definition given for "1st 5 Words of the Question" is "The 1st 5 words of the question text that are from the material and the interrogative word." This sounds like it's describing 6 words. And if the interrogative is the last word in a question longer than 6 words, this would refer to nonconsecutive words. Is there a reason to provide a definition for this term at all? I'd suggest deleting this term and definition, or rephrasing the definition to "The 1st 5 words of the question text, which may include an interrogative word as the 1st word."

**Comment by scottpeterson** [comment]
I like your rewording. 

I think the intent was "the first five words COULD include an inserted interrogative word, in which case the 'completed 1,2,3 word unique phrase' would need to occur in the "1st 4 non inserted interrogative words".

**Comment by jswingle** [comment]
+1 to @ARMediting 's rewording, I think that's much better.

**Comment by ARMediting** [comment]
On behalf of the Rules Committee:

During our meeting on 9/12/2022, the Rules Committee voted 5-0 to change the first definition in 10. from "The 1st 5 words of the question text that are from the material and the interrogative word" to "The 1st 5 words of the question text, which may include an interrogative word as the 1st word."

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md
