### ISSUE TITLE
1.2.2.4.3 Finish - first 5 words

### ISSUE THREAD

**Issue by jswingle** [gryphonshafer/Quizzing-Rule-Book#121]
```
1.2.2.4.3. Finish
Finish questions have question text consisting of the 1st 5 words of material starting based on the question type. These 1st 5 words must be unique to all possible finish questions of the exact same type; for example, FTV compared to all possible FTVs, FT to all possible FTs, F2V to all possible F2Vs, and FTN to all possible FTNs.
```

As written, it is a bit ambiguous whether the rules permit FTVs with _fewer_ than 5 words in the question. Do we want to allow these, or not?

E.g. 1 Corinthians 16:14 "Do everything in love." I think it would be fine to ask this as an FTV: "Do everything in..." so long as the words are distinguished from all other verse starts.

**Comment by jswingle** [comment]
Note that earlier versions of the rulebook were much clearer (in my estimation) that these verses _were_ allowed. Check out the [2018 rulebook](https://github.com/gryphonshafer/Quizzing-Rule-Book/wiki/files/Rulebook_2018.pdf)'s phrasing: "The quizmaster may give _no more than five words_ of the verse."

**Comment by ARMediting** [comment]
I've previously understood them to be legal, but what happens if one is read in full (say on a seat bonus)? It's simpler to rule them out than to describe how to handle the edge case in the rulebook.

**Comment by kclimenhaga** [comment]
I have always understood that they were not legal. For the few verses with 5 or fewer words, to me it makes more sense just to ask them in a different way, such as an INT or Q.

**Comment by jswingle** [comment]
> I've previously understood them to be legal, but what happens if one is read in full (say on a seat bonus)? It's simpler to rule them out than to describe how to handle the edge case in the rulebook.

In this case you just wouldn't read the full verse. 1 Corinthians 16:14 could be a three-word FTV: "Do everything in..." (assuming that no other verses in the material start with those 3 words.)

I'm struggling to think of any place in ANY material year where we would actually WANT to do this other than 1 Corinthians 16:14. There are a few other short verses I could think of, but they would all be terrible for FTVs in one way or another.

So I think it's totally fine if we prohibit these and just do them as Quote questions, but I think the discussion should still be had because this was an error in the original creation of this GitHub repository. The intent was to re-organize the rulebook and fix a few grammar bugs, _but make it functionally equivalent (FE) to the 2018 rulebook._ This rulebook language change seems to _not_ meet the requirements of FE, because I always interpreted the 2018 rules as allowing these while the current rulebook seems to prohibit them or is at the least ambiguous.

**Comment by jswingle** [comment]
I propose that we add a commentary section under "1.2.2.4.3 Finish" which clarifies that Finish questions must always be exactly 5 words to be valid. Even though previous versions of the rulebook allowed them, I don't know if this was the _intent_ or not, and I think the added value of allowing them is nearly nonexistent for reasons described above - particularly because we can always just choose to ask these short verses as Quote questions instead.

My proposed language:

1.2.2.4.4 Commentary
Since the question text must have exactly 5 words, a verse must be at least 6 words long to be a valid FTV question. Likewise, to be a valid FT question there must be at least 6 words remaining from the start of the sentence or quotation to the end of the verse. In either case, though, a F2V or FTN question could be asked at the same starting point, provided the total text of both verses is at least 6 words long.

--

Note that adding the Commentary section here will bump the current section 1.2.2.4.4 down to 1.2.2.4.5 instead, as well as all the other subpoints below it.

**Comment by ARMediting** [comment]
There's probably a shorter way to phrase Jeremy's suggestion.

Since the question text must have exactly 5 words, a valid FTV or FT must be six words or more total. Likewise, the full text of a FT2V or FTN must contain six or more words.

I'm also confused why 1.1.2.4. includes both quotes and finishes, especially when 1.1.2.4.3. acts as an introduction to finish types. Should they be divided to each have their own section?

**Comment by jswingle** [comment]
I like your shorter phrasing much better.

**Comment by gryphonshafer** [comment]
There are 2 separate but related topics embedded in the 2018 rule:

1. What's a legal question to write
2. What the QM is required to do

I think those 2 things shouldn't be merged together. We all agree the QM should have no discretion to read fewer words from the written question, ever (assuming a no jump). But should a question writer/editor have discretion to write Finishes with fewer than 5 words? (I personally think fewer than 5 is OK, but I don't have strong feelings about it.)

**Comment by jswingle** [comment]
@gryphonshafer What do you think about the argument I made above that it's simpler to just force it at 5 because there's possibly only one good verse in the entire material cycle that's fewer than 6 words?

**Comment by jswingle** [comment]
In the entire material cycle, though, even. I can only think of one good verse. I looked up a list of the shortest verses in the Bible and everything. There are a number of verses that are fewer than 6 words, but none of them would be good valid single-verse FTVs except that Corinthians one. The closest would be "Remember Lot's wife" lol.

**Comment by jswingle** [comment]
I like Alex's phrasing, and I'm proposing including it in the rulebook in the following location. Note that the current revision of the rulebook does not use bullet points in section 1.2.2.4.3, but I think with this additional rule it makes sense to add them so it's more readable.

ORIGINAL:

1.2.2.4.3 Finish

Finish questions have question text consisting of the 1st 5 words of material starting based on the question type. These 1st 5 words must be unique to all possible finish questions of the exact same type; for example, FTV compared to all possible FTVs, FT to all possible FTs, F2V to all possible F2Vs, and FTN to all possible FTNs.

--

CHANGE PROPOSAL:

1.2.2.4.3 Finish

- Finish questions have question text consisting of the 1st 5 words of material starting based on the question type
- These 1st 5 words must be unique to all possible finish questions of the exact same type; for example, FTV compared to all possible FTVs, FT to all possible FTs, F2V to all possible F2Vs, and FTN to all possible FTNs
- Since the question text must have exactly 5 words, a valid FTV or FT must be six words or more total. Likewise, the full text of a FT2V or FTN must contain six or more words.

**Comment by jswingle** [comment]
On behalf of the Rules Committee:

In a vote conducted by e-mail, the Rules Committee voted 6-0 to approve the change detailed below. This means that a "pull request" has been made - in other words, a change has been officially proposed and voted on by the Rules Committee, and will be given a final vote in 3 months. For the next 3 months, please view and comment on the pull request by following this link: https://github.com/gryphonshafer/Quizzing-Rule-Book/pull/151/files

A comparison between original language and the proposal we voted on can be found in my above post from Apr 25.

Technically, the language of the rulebook used to allow for FTV questions to be written with less than 5 words. However, in _practice_ it is rare, if not entirely unheard of, for a question writer to do this. Furthermore, the number of verses in the material cycle which are less than 6 words and would therefore require a FTV question to be fewer than 5 words, are very few and far between, and almost none of said verses would make for _good_ FTVs. So for the purpose of standardizing the Finish question type and removing any potential rulebook misunderstandings/discrepancies, we are now proposing _requiring_ exactly 5 words for all Finish questions, and spelling this out more clearly in the rulebook.

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md
