### ISSUE TITLE
1.2.2.2. word change

### ISSUE THREAD

**Issue by ARMediting** [gryphonshafer/Quizzing-Rule-Book#126]
In the MA section, the clarifier "The identification of a single pronoun does not meet the above requirement" is followed by "The identification of a plural pronoun, with more than 1 clarification to the pronoun, does meet the above requirement." 

Shouldn't "single" be "singular"? I would also advocate for removing the commas around "with more than 1 clarification to the pronoun," because they suggest that that phrase is the very definition of a plural pronoun, instead of denoting a certain type of plural pronoun.

**Comment by scottpeterson** [comment]
I do think "single" should be "singular."  Good catch!

**Comment by jswingle** [comment]
I prefer it with both of your changes!

**Comment by kclimenhaga** [comment]
I agree that single should be singular.

For the second suggestion, the wording is a bit awkward. Could we change it to "The identification of a plural pronoun does meet the above requirement if there is more than one clarification to the pronoun"? Or does that just make it more confusing?

**Comment by ARMediting** [comment]
The only reason I'd object to Kristen's suggestion is it renders the list nonparallel. Parallelism is helpful to me for clarity and ease of reading, but if it's not super clear, I'm fine with the change.

**Comment by jswingle** [comment]
+1 to Kristen's change, I think it's very clear.

**Comment by jttower** [comment]
Apparently my idea of parallel is different than Alex's.  The two proposals with changes:
1:
-The identification of a singular pronoun does not meet the above requirement.
-The identification of a plural pronoun does meet the above requirement if there is more than one clarification to the pronoun.
OR
2:
-The identification of a singular pronoun does not meet the above requirement.
-The identification of a plural pronoun with more than 1 clarification to the pronoun does meet the above requirement.

I prefer 1, but it's not a hill for me.  Although...should it be "more than one clarification OF the pronoun"?

**Comment by jttower** [comment]
Proposal:
-The identification of a singular pronoun does not meet the above requirement.
-The identification of a plural pronoun does meet the above requirement if there is more than one clarification of the pronoun.

**Comment by ARMediting** [comment]
Rules Committee voted on 4/10/22 to this change:

> -The identification of a singular pronoun does not meet the above requirement.
> -The identification of a plural pronoun does meet the above requirement if there is more than 1 clarification of the pronoun.

Vote passed 6-0.
