### ISSUE TITLE
4.2.2. Deity Rule word change

### ISSUE THREAD

**Issue by jttower** [gryphonshafer/Quizzing-Rule-Book#130]
As written:
The correct person of the deity must be given. The quizzer may not move between persons of the deity when answering. Giving the name of **a deity** that is not correct is considered giving incorrect information.

Proposed change:
"Giving the name of **the deity** that is not correct..."

Also in 4.2.2.1. Example:

As written: Examples of special names of **a deity** are:
Change: Examples of special names of **the deity** are:

(Simply change "a" to "the", as it is "the deity" in the rest of the section.)

**Comment by josiah-leinbach** [comment]
Agreed. I'd also suggest changing "between persons" to "among persons", since "between" is typically used when there are only two choices in question.

**Comment by jswingle** [comment]
+1 to both Jessica and Josiah's proposals.

**Comment by ARMediting** [comment]
Is there a reason we use "deity" and not "Trinity"?

**Comment by jswingle** [comment]
I'm not sure. I've always thought it was atypical to not use "Trinity" but I stopped thinking about it a long time ago lol. Traditions become ingrained. I would definitely support changing it to more typical theological terminology.

As written:
The correct person of the deity must be given. The quizzer may not move between persons of the deity when answering. Giving the name of a deity that is not correct is considered giving incorrect information.

Proposed change:
The correct person of the **_Trinity_** must be given. The quizzer may not move **_among_** persons of the **_Trinity while_** answering. Giving the name of **_a different person of the Trinity_** is considered giving incorrect information.

Notice the change from "when" to "while" and a slight wording change in the final sentence to be more precise (I think the original wording was awkward and kinda repeating the same thing twice, that giving an "incorrect" person equals "incorrect" information)

As a side note, I don't know that the second sentence above is even necessary. If they can't give the name of the wrong person, it automatically means they can't move among the persons.

**Comment by jttower** [comment]
I agree with changing any mentions of "deity" to "Trinity" and I like Jeremy's proposal. I am also fine with deleting the second sentence, which does seem redundant.

**Comment by JoshJetto** [comment]
I agree with Jeremy's proposed change.

**Comment by jswingle** [comment]
Under 4.2 Rulings, "special name" is defined:

`A name that imparts specific character qualities or attributes to that person of the deity
`
Changes to:

`...that person of the **Trinity**
`
```
4.2.2. Deity Rule
The correct person of the deity must be given. The quizzer may not move between persons of the deity when answering. Giving the name of a deity that is not correct is considered giving incorrect information.

If a quizzer refers to any person of the deity as either "God" or "Lord", these must be clarified by the quizzer within the question answer duration period when the text requires a more specific answer.

"Jesus" and "Christ" are interchangeable (but refer to the person of the Son) and the quizzer will be called correct.

If a pronoun is used in the text to name the deity, any of the names for that person of the deity within context may be considered an acceptable answer when clarifying. If the pronoun naming the deity is identified by the quizzer using a name that correctly identifies the deity, but with an identification that is out of context, the quizzer will be considered to have not stayed in context.

When there is a special name of the deity given in the text, the special name must be given in the quizzer's answer. If the quizzer states any other special names which are not in context, the quizzer will be considered to have not stayed in context, even if they refer to the same person of the deity.

When a quizzer gives other names for the same person of the deity, used within context, these should be allowed to be clarified within the question answer duration period when a more specific answer is needed.
```

Proposed change to:

`4.2.2. Trinity Rule
The correct person of the **Trinity** must be given. **sentence removed** Giving the name of **a different person of the Trinity** that is not correct is considered giving incorrect information.

If a quizzer refers to any person of the **Trinity** as either "God" or "Lord", these must be clarified by the quizzer within the question answer duration period when the text requires a more specific answer.

"Jesus" and "Christ" are interchangeable (but refer to the person of the Son) and the quizzer will be called correct.

If a pronoun is used in the text to name **a person of the Trinity**, any of the names for that person of the **Trinity** within context may be considered an acceptable answer when clarifying. If the pronoun naming **that person of the Trinity** is identified by the quizzer using a name that correctly identifies the **person of the Trinity**, but with an identification that is out of context, the quizzer will be considered to have not stayed in context.

When there is a special name **for a person of the Trinity** given in the text, the special name must be given in the quizzer's answer. If the quizzer states any other special names which are not in context, the quizzer will be considered to have not stayed in context, even if they refer to the same person of the **Trinity.**

When a quizzer gives other names for the same person of the **Trinity**, used within context, these should be allowed to be clarified within the question answer duration period when a more specific answer is needed.
`

**Comment by josiah-leinbach** [comment]
Prosed change: 

"4.2.2.1. Example

Examples of special names of **God** are: ... "

**Comment by jttower** [comment]
Proposals:
"The correct person of **the Trinity** must be given. Giving the name of a different person **of the Trinity** is considered giving incorrect information."
And replace "deity" with "Trinity" except in a couple of instances when changing it to "God":
"When there is a special name **of God** given in the text,"
"4.2.2.1. Examples of special names **of God** are:"

**Comment by jttower** [comment]
Rules Committee voted 3/20/22 on the latest proposed change.
Vote passed 6-0. 
On behalf of the Rules Committee, this issue is closed.
