### ISSUE TITLE
2.2.1.1.1. Change "Identify" Back to "Clarify"

### ISSUE THREAD

**Issue by ARMediting** [gryphonshafer/Quizzing-Rule-Book#134]
While I do think clarification is a slightly better description than identification of what a quizzer is doing when asked to "Identify," my main reason that we should change this rule back is because "Identify" is four syllables compared to three for "Clarify." It's harder to say as well. (I also find it amusing that the RB section header for the rule is titled "Pronoun Clarification.")

I'd also like to adjust the official phrase from "Can you clarify ___" to "Clarify ___." I couldn't find this wording in any previous rulebooks, but I imagine most of us have heard or used this shortening. It gives the quizzer more of their answering time, often at a crucial point toward the end.

**Comment by jttower** [comment]
I agree with Alex. I prefer "Clarify ____" for it's brevity.

**Comment by jswingle** [comment]
This issue is more or less identical to https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/37 - I'm going to close this one out and link to this issue over there.
