### ISSUE TITLE
Unique Word Answer Requirement

### ISSUE THREAD

**Issue by Jabberwocky415** [gryphonshafer/Quizzing-Rule-Book#144]
According to the rulebook section 4.2.3 “_The quizzer’s answer must include all unique words in both the question and the answer._”
Stated more simply, it just means a quizzer may not substitute any word in place of a unique word when giving their answer. 
This rule has recently (to my knowledge) come under serious scrutiny regarding it’s necessity and value to the program. While I believe it’s always good to be evaluating our ruleset and changing things for the better, this rule is one I believe must stay. I would like to make arguments for the value of unique words in both **objective rulings** for officials, and **study aides** for quizzers.

Before I continue, let me explain what I believe unique words mean to quizzing. I would wager that close 90% of them are words we wouldn’t want substituted in an answer anyway. They represent a specific idea, object, or person that means something very unique to the passage they’re found in. They, I believe, lay the very basic foundation of what sets one passage apart from another. And the other 10%? I’ll get into that a bit more later on, but here I’ll just say they do the same job as the others without being as obvious about it.

### Objective Rulings
Having a clear line that a quizzer must cross to be counted correct means less ways for a quiz to be delayed by long official debates on answer “rightness”, and makes it easier for quizzers to understand why they were counted incorrect. 
I think any rule revision in this area of the rulebook should make it easier for officials to make their decisions, not harder. Unlike some, I do not believe all manner of interpretative power should be removed from the quizmaster/answer judge’s duties. However, I definitely don’t think we need any more of that than what we’ve got right now. There’s no need right now to make the work of deliberation more difficult for the official’s table, which is exactly what removing this rule would do. I’d guess that if we stopped requiring quizzers to give all unique words, we might increase the number of hard decisions by at least 20-30% per quiz _on average_. 

This does two things: it means quizzes get longer on average—which leads to faster quizzer burnout/exhaustion as the meet goes on, and it also assuredly ups the chances of a quizzer feeling like they got cheated out of being counted right. While it’s true that not every unique word would be 100% “irreplaceable” under normal circumstances, at least quizzers know exactly why a ruling didn’t go their way if the rule is explained correctly. Leaving it open to interpretation invites confusion and potential resentment. 

Now a counter-argument might say: “But Andrew, we already allow QM’s to interpret answers that don’t involve unique words. How is this different?”
This is a valid critique, but one that I believe is missing the point. On one hand, complete objectivity in rules gives us the smoothest quiz experience for all parties; on the other hand, complete subjectivity would allow us to make the “right” decision in every circumstance, and give more leeway for quizzers who know the material at a more basic level. I would argue strongly this rule is the best middle ground. What we want to do is limit unnecessary quizmaster interpretation, _to a certain point_. And right now—from my perspective as an official, coach, and former international quizzer—the mix is just about right.

### Challenging
I want to quickly mention this subject. I’m the biggest advocate for challenging you will find. As a quizzer, I was willing to challenge anything and everything that resembled a gray area. And if you have the courage, I would encourage any quizzer to do the same when the situation calls for it. Right now I would say opportunities for gray area challenges come up 3-4 times a quiz. Sometimes less, sometimes more. And most of those, the vast majority, go unchallenged. That’s not a bad thing, as most of the time a good argument is hard to form, and the risk of losing is not worth the chance at a small reward. However, if we didn’t have the unique word rule, I think that opportunity count goes up to 5-6 times per quiz, but I actually think the number of challenges would go up a disproportionate amount. 

The unique words would (presumably) still be highlighted in the material, and most captains would know that a challenge is much easier to make when you can point out that the missing word in an answer was unique, rule or no rule. More challenges mean more deliberations, which means longer quizzes, and quizzers more exhausted from both the long quizzes the stress of hard decisions. 

### Study Aides
When I first started getting serious about memorizing, I was recommended a mental recall device by some veteran quizzers, “When you quote, snap on the unique words.” This helped in two ways. The more obvious but less helpful advantage was to remember which words were unique in a given verse. But the more helpful side effect was actually giving every verse a unique rhythm and meter in my head and on my tongue. They give structure to what otherwise might look like an intimidating wall of text. 
Even if you don’t do the snapping thing, just making a tiny mental note when reciting a unique word helps with recall in the future. Knowing unique words makes memorizing the rest of the material more simple, which in turn makes remembering those unique words easier. That’s the same for even the 10% of words I mentioned were less “irreplaceable”. They’re sign posts that guide a good study habit. 

“But Andrew, couldn’t you do all that anyway? We don’t need the rule to make study effective.”
Well, I think it’s more complicated than that. This is where we need to talk about **incentive**. If our objective for this program is for kids to learn the Bible stories and understand some of the lessons, maybe we wouldn’t need the rule. But if our objective is for the kids to _memorize scripture_, the rule is immensely valuable. See, memorization is the core of Alliance Bible Quizzing. When we ask our questions, we’re checking for memorization. Every question type is designed to test it in different ways. Maybe some other quiz programs test for different things, or have question types and formats that reward a different (no less valid) way of learning God’s word. 
But this is how our whole program is designed. And the unique word rule is a core part of our testing process. 

When a kid commits to the task of memorizing material and participating in this program, it’s with the understanding that they’ll be quoting back that material on stage the same way they read it in the book. And no amount of leniency on our part regarding how to accept their answer’s should take away that expectation. A clear understanding of what the program expects of them gives quizzers a goal, a goal gives them drive, and drive gives them passion. Every quizzer has their own way of memorizing, and that’s a good thing. But forcing them to know the unique words is a quick, easy, fair, and effective way to test whether they actually _have_ memorized, and not just skimmed. 

I believe the intent of the rule is to separate a good answer from lazy one. That may sound harsh, but competition only works if there’s a good reason to work to get better. Quizzers can get by on having just a good understanding of what goes on in the book we’re in. But they will get checked again and again by these tests. And the only way to take the next step is to memorize.

**Comment by jswingle** [comment]
@Jabberwocky415 Hi Andrew - we already have an open issue on this topic, so I'm going to close this one out and link to it on the main thread. You're also welcome to copy+paste what you've written here if you like, but I will at least link to it.

https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/109
