### ISSUE TITLE
1.2.2.1 Unique phrase requirement revision

### ISSUE THREAD

**Issue by jswingle** [gryphonshafer/Quizzing-Rule-Book#145]
```
Unique Phrases
2 or 3 consecutive words appearing in only 1 verse in the material
```

`
1.2.2.1 Interrogative (INT)
Must include a unique word or a 2 or 3-word unique phrase within the 1st 5 words of the question
`

I would like to do away with the concept of "unique phrases" from the rulebook entirely. In my judgment, as long as the INT or MA question is _identifiable to a unique location in the material_ within 5 words, it should be considered valid. This means that instead of searching up to three separate 3-word phrases for uniqueness, a question writer is free to put in all the first 5 words (or words 2-5, if the question begins with the interrogative word) and check the entire sequence of words for uniqueness.

This is just a hypothesis, but I would guess this is the only reason unique phrases are defined this way: in the era of quizzing before everyone had easy access to searchable material, question writers had to rely on unique word/phrase lists in order to know if the INT or MA they were writing was unique. For simplicity's sake, these printed lists were capped at 3 words. This is no longer an issue for anyone, and now this once-prudent limitation is sort of just in the way and unnecessary. It adds a small amount of time to question writing to have to check additional sequences of words, without any tangible benefit that I can see.

Another reason to change the rule is that it's unintuitive, due to its inconsistency with the similar-but-different 1st 5 words rule concerning Finish questions. Since Finish questions only require the whole sequence of 5 words to be unique, many automatically assume the same for INT/MA questions. I've talked to some long-time question writers and answer judges who weren't even aware of this rule, and I understand why. It's only maybe 1 in every 1000 INT/MA questions where the rule prohibits a question that would otherwise be valid. We should keep the rules as simple as possible, and only introduce or keep complex rules if they add a lot of value. "Unique within the first 5 words" is much simpler than "unique phrase within the first 5 words, and here's the specific definition of a unique phrase"

**Comment by gryphonshafer** [comment]
> This is just a hypothesis, but I would guess this is the only reason unique phrases are defined this way: in the era of quizzing before everyone had easy access to searchable material, question writers had to rely on unique word/phrase lists in order to know if the INT or MA they were writing was unique.

I can confirm your hypothesis. This is _exactly_ why. Ergo, I agree; the 2-3-word stuff should be burned.

**Comment by jonathanvanschenck** [comment]
I totally agree with your argument.
Is there an argument here to also do away with all references to "unique words" as such? I believe the only other relevant rules about unique words are about context -- but those sections also allow for quizzers to be called out of context for vaguer reasons that just "a unique word from more than 5 verses away" I'm not sure we gain anything on except gotchas for newbies.

**Comment by jonathanvanschenck** [comment]
Wait ... But I didn't we already get rid of the "one word makes you out of context" rule a while ago? Ya, we should totally just nuke the whole notion of "unique thing" -- either something is identifiable or not, the only limit should be the 5 word cap for question writing.

**Comment by jswingle** [comment]
@jonathanvanschenck I would agree that logically, implementing the change I've outlined here would also lead to getting rid of the concept of "unique words" in the rulebook as well (although it would still very much be a term _outside of the rulebook_ when it comes to quizzing preparation and the printing of materials with bolded words)

However, there's an entire giant discussion going on concerning the "unique word required" rule, and it's not yet known whether this rule will end up staying in the next revision of the rulebook: https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/109

So I decided to not throw this wrench into the mix for now. If that rule gets deleted from the rulebook, the definition of "unique word" should also go away too at some point in my judgment.

**Comment by jonathanvanschenck** [comment]
I'll check that discuss out

**Comment by ARMediting** [comment]
Definitely adding my support to Jeremy's proposal. It adds a good degree of difficulty for quizzers and expands the number of potential questions that can be asked.

**Comment by scottpeterson** [comment]
I agree with everything said. I will nitpick you Alex; I think the degree of difficulty added is incremental at most. There's hardly questions that I would rather write as an INT (as opposed to reference question) that don't have a completed 1-2-3 word unique phrase in the 1st 5 words, but ARE unique in the 1st 5 words. So I think the added difficulty would be extremely marginal.

**Comment by jswingle** [comment]
It's worth reiterating in line with @scottpeterson that there is a VERY TINY number of questions that would suddenly become valid if we implemented this proposal. It's maybe on average 10 questions per quiz year. I almost never see instances where a question is "unique in 5 words" but has no "unique 3-word sequence in 5 words" 

The point is less that it would change the question set for the better, and more that it would make question writing/editing much easier and the rules simpler.

**Comment by kclimenhaga** [comment]
I agree that removing unique phrase rules is a good idea, as long as it is clear that a question must be unique within the first five words.

**Comment by JoshJetto** [comment]
I agree with this proposal. It's a good change that is not only better for question writers but more understandable to a wider audience reading the rulebook.

**Comment by ARMediting** [comment]
I don't love the wordiness of that proposed text. The need to begin with "Must" is limiting our options. What about: 

> 
Must have the 1st 5 words (or 4 if one is the interrogative word) appear in order in only a single verse in the material.

**Comment by jswingle** [comment]
On behalf of the Rules Committee:

During our meeting on 11/06/2022, the Rules Committee voted 6-0 to keep this issue in discussion for now. This means we have neither rejected or approved this issue, but would like more input before we decide.

We are more or less in agreement with the idea behind this rule, but are interested in working more on the wording to it and taking an e-mail vote. 

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md

**Comment by ARMediting** [comment]
Commenting on this to re-up it for those interested. We did take a stab at some language last committee meeting:

> Must have the 1st 5 words (or 4 if one is the interrogative word) appear in order in only a single verse in the material or in only one instance.

Our concern is making sure corner cases are all covered. Like, what if a phrase spans two verses? What if the identical phrase appears twice only in one verse? Is there a much simpler way to do this we're not thinking of??

**Comment by JoshJetto** [comment]
I like Jeremy's wording. I would amend it to the following to cover instances where a phrase or question may span two verses: 
"Must be uniquely identifiable either to a single verse or to a single instance in the material within the first 5 words of the question."

**Comment by jttower** [comment]
I like Josh's wording, but would it mess anything up if we just said:
"Must be uniquely identifiable either to a single instance in the material within the first 5 words of the question."
My reasoning is because if it is in a single instance in the material, that would also cover if it was in a single verse, wouldn't it?

**Comment by josiah-leinbach** [comment]
On 1/7/22, the Rules Committee voted to amend the third bullet point in 2.2.2.1 as follows:

"Must be uniquely identifiable either to a single verse or to a single instance in the material within the first 5 words of the question."
