### ISSUE TITLE
REF/Quote Questions - Clarification of When Quizzers have Given a Definitive Reference 

### ISSUE THREAD

**Issue by shamwow2319** [gryphonshafer/Quizzing-Rule-Book#159]
The rulebook would benefit from additional examples regarding when Quizzers are considered to have given a definitive reference. 

This is particularly relevant for verses that start with twenty-, thirty-, etc. It's often obvious when quizzers are searching for twenty-something, compared to verse 20. We should be able to trust quizmasters to have discretion as to whether a quizzer is fishing or genuinely trying to understand what they've heard/seen the quizmasters saying. 

I would suggest adding an example or some wording under 4.2.4 to say "a quizzer who has said twenty-, thirty-, etc, will not be considered incorrect if they appear to be searching for the correct verse that starts with twenty, thirty, etc."

Probably some work to be done on the wording and to avoid fishing, but open to discussion

**Comment by levikoral** [comment]
I agree because some people you can tell are searching for a verse.

**Comment by scottpeterson** [comment]
Isn't it just simplest and change nothing?  If a quizzer says a verse number that COULD BE continued (e.g. "twenty" "thirty"), the QM doesn't rule anything until the quizzer says some of the verse (and this able to conclusively put the quizzer in a context.   If the quizzer says something like "four" that can't be continued the QM can rule immediately. 


Personally, if a quizzer says "Twenty" with the full inflection and pauses for a few seconds, I will just rule then. And if they challenge saying they were gonna continue the verse number, I'd (a) overrule the challenge, (b) foul them for an infraction against the spirit of quizzing.   You just can't allow obvious fishing/phishing like that.

**Comment by jttower** [comment]
I agree with @scottpeterson here. At one point (at least in our district) we required quizzers to start quoting the verse before making a ruling, which made them commit to a verse. The QM would just stay silent until that point. Therefore, if we do add anything, it could be as simple as that.

**Comment by kclimenhaga** [comment]
I'm in favour of ruling immediately when a quizzer has said twenty-four, twenty-five, and so on, since even if they quoted the correct verse (e.g. said "twenty-five" but then quoted verse twenty-four), we would have to call them incorrect for having given the incorrect verse number. When a quizzer just says "twenty", I will wait for them to start the verse, even if I'm confident they are just going for verse twenty. That makes things simpler and prevents challenges.

**Comment by jswingle** [comment]
This came up in my room at 2022 Internationals. We had a challenge precisely because I _misinterpreted_ the intent of the quizzer to continue. It may be more difficult to consistently interpret the quizzer's intent than we think.

I don't know that any rule changes would _fix_ the situation perfectly, though. Open to suggestions, but I don't like the idea of trying to define it.

**Comment by josiah-leinbach** [comment]
I think the best solution is, as @scottpeterson said, change nothing. Simply count the quizzer incorrect once they either give the wrong verse number or quote the wrong verse. If the quizzers "searches" for the right verse number, does not settle on one, but ends up quoting the right verse, they would still need to give the right verse number to be counted correct.

**Comment by jttower** [comment]
I don’t think we need to change anything in the rule book. The QM just waits until the quizzer has given incorrect information, whether that be starting in the wrong verse or saying the wrong number. If the quizzer stands up and says “twenty…” then the QM remains silent until they either say another number or start quoting a verse.

**Comment by jswingle** [comment]
I think I agree. This is the mistake I made when I was QMing on this issue - I should have permitted the quizzer to continue answering until they either said a longer number, or began quoting.

Not an issue that requires a rulebook change -- just an issue that required me to quizmaster better.

**Comment by ARMediting** [comment]
On 4/2/2023, the Rulebook Committee voted 6-0 to close this issue with no action.
