### ISSUE TITLE
Stricter rulings on answers to reference questions

### ISSUE THREAD

**Issue by Jabberwocky415** [gryphonshafer/Quizzing-Rule-Book#161]
I think a strong area of trouble for ruling on certain reference questions lies in determining when a quizzer can be called out of context. This comes into play especially in cases where the reference question in question has two answers which are similar; how do you decide if a quizzer has answered the question with the answer from a different context? An unspoken convention seems to be that a QM can make the decision that even if a quizzer gave a “similar” answer to the one written, if it’s too similar to a different answer to the same question they will be ruled out of context. 

I propose we make this a more definitive rule.
An example of what I mean is from Acts 15, in verse 11 we read “the grace of _our Lord Jesus_”, and in verse 40 we see “the grace of _the Lord_”. If a quizzer jumps on a CVR on verse 40 and says “the grace of our Lord Jesus”, I think most people would agree they should be wrong, if only for the “Trinity rule (that feels weird)”, however I propose we do the same for the inverse scenario. If a quizzer jumps on a CVR on 11, and answers “the grace of the Lord” verbatim, they would be incorrect under this rule.
After all, isn’t the point of a reference question to allow a quizzer to show they can differentiate between two similar passages in the material?

Obviously this rule would have to supersede the normal Trinity Rule and out of context rules for reference questions specifically. 
I think the wording should be something like:
`If the answer given is identical in wording to an answer to the same question in a different context, the quizzer will be ruled out of context`

This may feel a bit extreme, but I think it removes a lot of trouble for officials when ruling on references.

**Comment by jswingle** [comment]
Closing out as identical to issue #129 - discussion can be continued there!
