### ISSUE TITLE
Change "Challenge" to "Appeal"

### ISSUE THREAD

**Issue by josiah-leinbach** [gryphonshafer/Quizzing-Rule-Book#165]
In keeping with my logic in Issue #33 regarding "protests", I propose changing the term from "challenge" to "appeal" in the rulebook.

The short version of what I argued in Issue #33 is that words have connotations. Both of the terms "protest" and "challenge" seem  abrasive, confrontational, and overly dogmatic, both for the atmosphere we want to foster as well as what the actions seek to accomplish in a quiz. Currently, we use phrases like, "So-and-so challenged against so-and-so," and while no one means any malice, it can make it seem as if the whole process is about the people. "Appeal" is neutral word that focuses less on the people involved (e.g. the quizmaster, the quizzer, etc.) and more on the rules/logistics.

**Comment by jswingle** [comment]
I think it was much more of a priority to change the word "protest," but I'm definitely open to a new term for "challenge" and now would be the time to change it so that the terminology can change at the same time.

"Appeal" seems like a good term to me, but I'm open to additional suggestions!

**Comment by gryphonshafer** [comment]
"Appeal" has some history and traction in other quizzing programs. World used it (back when World was awesome). Another option might be "reconsideration", which is technically a bit more accurate to what's going on, but that's got a lot of syllables. So I think "appeal" is the right word to go with, since we could describe it as an "appeal to reconsider" a ruling.

**Comment by jswingle** [comment]
Worth referencing the discussion here on the word "protest" : https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/33

**Comment by jttower** [comment]
I like appeal better as well.

**Comment by ARMediting** [comment]
Rules Committee voted on 11/6/22 to:

Change all instances of “challenge” or any forms of it to “appeal”  or any forms of it in the rulebook.

Vote passed 6-0.

**Comment by jswingle** [comment]
This issue was never closed, though a pull request was made and has already been put into the integration branch. Closing now.
