### ISSUE TITLE
Changes in Numbering in Full-Content Rulebook Render

### ISSUE THREAD

**Issue by ARMediting** [gryphonshafer/Quizzing-Rule-Book#166]
The various renders can affect the numbering of various rules because the logic sections add a number at the beginning of a section. See the differences in the screenshots below:

![standard](https://user-images.githubusercontent.com/98666298/189505610-43875cb0-38b3-49d2-977b-3c1c8580e090.jpg)
![full](https://user-images.githubusercontent.com/98666298/189505612-20de879b-9409-405b-aaf2-15b100d97644.jpg)

________

I propose to either denote logic sections with a different numbering, such as roman numerals or an "x" or something; or placing the logic at the end of each section instead of the beginning, so the numbers aren't reordered.

Although it's likely few people use this render in daily life, someone may download or use it by accident, or someone who refers to the logic section may forget and write an issue referencing it.

**Comment by gryphonshafer** [comment]
Remember that section numbers are different between every build type of every iteration release. They're only a quick way to reference a section in a single document, not compare across documents.

**Comment by jswingle** [comment]
@gryphonshafer I find it more or less necessary to use section titles to describe things, particularly when the discussion concerns exactly how to format the rules, whether to use a sub-point or not, etc.

The revision numbers will only change once a year, and in future revisions after 2023, I don't think there will be a whole lot of issues which actually stay open for a whole year. So this is only a temporary problem.

**Comment by gryphonshafer** [comment]
Using section titles (with the text, not the numbers) is completely reasonable; one can use the GitHub search tool to find that text. I'm just advising not to use section numbers, because they're unreliable between builds and releases.

The most reliable method (which also turns out to also have the highest reader usability) is to click on the little link icon that appears when you mouseover a title, then copy that into a link. For example:

[Types of Quizzes](https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/cefb97677be93b1f0882a43bcb3839d3aafa1a09/rule_book/03_quiz_process.md#types-of-quizzes)

**Comment by jswingle** [comment]
Ah, that's a great idea. 

That being said: many of the sections are titled identically, so it's not sufficient to just use the section titles. The links work though.

**Comment by ARMediting** [comment]
I'll try to use the linking more; but in our work on the rule committee, the numbers have been extremely helpful for easy reference and discussion.

**Comment by ARMediting** [comment]
The Rules Committee voted 5-0 on Jan. 7, 2023, to close this issue without change. We have recognized the potential confusion various renderings could cause, as well as future updates that could add or remove top-level numbering, as happened this year. We will connect with Gryphon and learn whether there are strategies to avoid this in the future.
