### ISSUE TITLE
Team Points for Third Person Bonus/3PB on Bonus Questions

### ISSUE THREAD

**Issue by jttower** [gryphonshafer/Quizzing-Rule-Book#169]
It was brought to my attention that there was some discussion and confusion regarding the third person bonus (which I will call 3PB for brevity, and because it's cool to do so).  :-)  The discussion was whether answering a bonus question could count as a 3PB/4PB/5PB.  In practice I have never seen this to be the case, but that the 3PB/4PB/5PB was awarded for jumped on questions.  Upon scrutiny of the rule book, apparently they couldn't find that this was explicitly stated as being the case since the current rule states
**"+10 points for the 1st correct answer given by the 3rd and subsequent quizzer on the team"**
The argument was that if a quizzer answered the bonus correctly, then that should also qualify them for the 3PB.

**Comment by shamwow2319** [comment]
My understanding was that the idea was to reward for 
1. Answering correctly, but also
2. Winning the jump

At internationals specifically this would be quite relevant, where winning the jump is much different than being awarded a bonus. I think this is one that districts could easily modify for their levels of quizzing if they so wished. Unsure how to clarify this in the rulebook language, but I believe the intent/"unwritten" portion of the rule should hold, where the bonus only applies to jumped questions

**Comment by JoshJetto** [comment]
This rule should be amended with the addition at the end "excluding bonus questions."

**Comment by jttower** [comment]
The Rules Committee unanimously voted on 11/17/22 to add "excluding bonus questions" as mentioned above.  The new wording will say, under 
[6.1.2. Team Points](https://gldg.us/gh/gryphonshafer/Quizzing-Rule-Book/releases/latest/download/rule_book_std.html#h3_87_teampoints)

    6.1.2.1. Points Earned

    +10 points for the 1st correct answer given by the 3rd and subsequent quizzer on the team, excluding bonus questions.
