### ISSUE TITLE
Hyphenated Words

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/Quizzing-Rule-Book#21]
Should hyphenated words be defined as a single word, for unique word and unique phrase definition purposes? (also first five "words" of a question")

**Comment by kclimenhaga** [comment]
I have always treated them as one word when writing questions. For this year's material, the hyphenated words are:
non-Greeks, God-haters, self-seeking, ever-increasing, co-heirs, co-workers, co-worker, double-minded, full-grown, peace-loving, self-indulgence

Normally, "co" on its own is not a word in English, so I would not define co-heirs or co-worker as two words. This is in line with what I see in the purchased texts and other materials.

Do we have instances were people are defining hyphenated words as two words? If so, maybe we need to clarify this in the rulebook.

**Comment by gryphonshafer** [comment]
Just as an FYI: CBQZ considers a hyphenated word to be 1 word. However, this practice is not explicitly defined in the current rule book.

We probably want to consider the difference between a hyphen, en dash, and em dash. NIV uses em dashes, so to keep things clear, CBQZ converts these to double hyphens. (CBQZ also converts en dashes to single hyphens, though I don't think en dashes exist in NIV.) Thus, a "word hyphen word" is considered 1 word, but a "word hyphen hyphen word" is considered 2 separate words.

**Comment by jswingle** [comment]
+1 on hyphenated words being considered a single word. In addition to making the most grammar sense, this is what every printed material I've seen does anyways. No reason to change what seems to be the consensus already.

**Comment by gryphonshafer** [comment]
Might be a good idea to note this explicitly somewhere in the rule book. Just a single little sentence in the right place would be enough.

**Comment by jswingle** [comment]
Agreed that it should be explicit in the rulebook. Simple to do.

**Comment by jttower** [comment]
@gryphonshafer would you be willing to write up a proposed rule for this?

**Comment by gryphonshafer** [comment]
How about this:

> 2 words separated by a single hyphen or single en dash are considered a single word.

Shorter alternative:

> Whatever CBQZ considers a single word is.

(Just kidding.)

**Comment by jswingle** [comment]
@gryphonshafer I think there's no need to complicate things with the language of en/em dashes. When the NIV uses the em dash, it's always clear that it's not a hyphen. I think we could go with something simpler:

> Hyphenated words count as one word. Examples: peace-loving, co-workers, super-apostles, double-minded

**Comment by kclimenhaga** [comment]
The Rules committee voted on April 2 to add the following to the definition of 1st 5 Words of the Question in section 2:

Hyphenated words count as one word. Examples: peace-loving, co-workers, super-apostles, double-minded.
