### ISSUE TITLE
MA as a sub-type under INT

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/Quizzing-Rule-Book#32]
Move MA to be a sub-type under INT, so INT/MA fall under same type distribution guidelines.

Reasoning: CVR and CVRMA are fundamentally the CVR structure of question--so fall under the CVR (and thus Ref) type distribution guidelines.

MA and INTs are fundamentally the same structure, so be consistent.

Counter-reasoning: we think MAs are special enough that we want to carve out a type just for them.

Since we reduced the MAs down to 1, they are such a minor point of every quiz, guaranteed. Which is mostly fine, since we wanted to create more rewards for the Question Types that require more material memorization. But there's no reason we can't include MAs with INTs, and randomly you may get 0 in a quiz, or 4 in a quiz.

**Comment by zctinker** [comment]
Here Here!

**Comment by scottpeterson** [comment]
Willing to explore elimination of MAs as a type altogether.

BUT, I think problems arise on Refs, if the quizzer needs to provide a question and they don't know if the required answer has 1 or > 1 answer.

There are also SOME problems on split MAs....the question portion is valid and clear, but having to answer 2 answers that are NOT contiguous, when you don't know if there are > 1 answer, could be problematic.

**Comment by kclimenhaga** [comment]
I would not support removing MAs as a question type altogether, since there are some instances where a valid MA is a confusing or invalid INT. If we did remove this question type, we would need to reword the section that talks about a question with two possible answers being invalid. Combining MAs and INTs in the question distribution could solve a lot of the problems we have with MAs.

**Comment by JoshJetto** [comment]
I also disagree with making MAs a sub-type of INTs. I have outlined my reasoning for that in the issue post 3.4 Question Type Distribution - On Behalf of Josh Jetto.

**Comment by jswingle** [comment]
There's good logic to the point that we already have CRMA/CVRMA as a Reference subtype, but even if we made MA a subtype of INT, I would want the rules to require a minimum of MAs. It would be more of a semantic change than a practical change, thus not really much of a value add.

I'm generally in favor of rethinking the MA question type, though. Open to ideas. There's a lot of problems with defining what makes something an MA at the moment.

**Comment by scottpeterson** [comment]
I think it makes a lot of sense to do these things in order:
(1) Move MAs as a subtype under INTs. 
(2) change the INTs minimum to be [ current INT minimum + current MA minimum] and do the same thing for INT maximums.

(3) Have a larger discussion on relative value of each question type, and potentially alter minimums/maximums. (That feels like a much more general, larger, long-term discussion).
(4) Have a larger discussion on whether the difficulty in defining MAs could be solved by removing the type altogether. If that happens, the INT min/max shouldn't change, since at that point we're treating INT/MA as the same "structural type"

IMO, the "should we move MAs to be a subtype under INTs" should not be conflated with the much different "let's look at question type distribution again" conversation.

**Comment by scottpeterson** [comment]
And frankly if:

( MA min / INT min ) < ( # of written MAs / # of written INTs), then doing (1) would result in MORE MAs asked. 

That does bring up again the Pandora's box issue of: "Are we fine with written proportions of subtypes becoming the asked proportions, because we should be generating question sets randomly?"

**Comment by ARMediting** [comment]
Scott, are you thinking that MAs would still be announced as multiples, the way CVRMAs are? The QM would call them "Interrogative-Multiple Answer" during the lead-in? The only thing that changes is distribution, which the rules committee recently revised anyway.

**Comment by kclimenhaga** [comment]
Rules committee voted to close this issue without making changes. The question distribution has changed since this proposal was first made, so any discussions about Multiple Answer questions need to be considered in light of the new distribution. Participants are welcome to make new proposals about Multiple Answer questions once the new distribution has been implemented.
