### ISSUE TITLE
Pronoun Clarification QM Prompt

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/Quizzing-Rule-Book#37]
Other QM prompts don’t have lead in words like “can you.”  Just ditch them and change this to “Identify [pronoun]” or “Clarify [pronoun]”.

And the correct choice is “Clarify [pronoun]”.

**Comment by gryphonshafer** [comment]
“Clarify [pronoun]” is the only reasonable choice. This is a hill I will die on.

**Comment by kclimenhaga** [comment]
I agree that "clarify" is better wording than "identify". I don't have strong feelings on the "can you" part.

**Comment by jswingle** [comment]
I'm closing out this identical issue and linking the discussion for consideration here:

https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/134

**Comment by ARMediting** [comment]
I thought I'd looked thoroughly enough to find if someone had already done this! Thanks, Jeremy.

**Comment by jswingle** [comment]
100% to @josiah-leinbach 's proposal. 

Do we also want to specify a template for when a question includes multiple clarifications? For example, "Clarify [PRONOUN] and [PRONOUN]." There is no rule presently against having multiple clarifications, and I don't think there should be, so there should be a prompt for QMs to follow.

**Comment by jswingle** [comment]
If a quizzer has provided all the information in the question and answer, except the identification of a pronoun present which is part of the answer text, the quizmaster will prompt the quizzer to clarify the pronoun by saying, "Clarify [pronoun]."
