### ISSUE TITLE
Rebuttal - formerly define for ease of use

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/Quizzing-Rule-Book#39]
"When a challenge is made, the quizmaster must give each team’s captain or co-captain an opportunity to speak to the challenge before making a ruling on the challenge. Whichever team is being challenged against will have the right to speak last."

Define this.

**Comment by ARMediting** [comment]
Just noting that "rebuttal" could also be used for clarity in 2.1.1. Captains. Do we have a precedent of allowing a definition before the first use of that term? (It's not like it's a completely confusing term standing on its own.)

**Comment by jttower** [comment]
I don't think this section is confusing as worded so I'm not convinced it needs to be changed or defined.  I think it's pretty clear that each team's captain will have a chance to speak if there is a challenge.

**Comment by jswingle** [comment]
@scottpeterson What, specifically, do you think should be defined? I don't see a problem with the rule as presently worded, and I'm not sure which part of it needs a definition.

**Comment by scottpeterson** [comment]
yeah I should've written more text. I can't remember why I opened this.

**Comment by jswingle** [comment]
So you're saying we should close it out? =)

**Comment by scottpeterson** [comment]
carry on. If it's important I'll remember and open a ticket with far more information and proposed wording.

**Comment by jswingle** [comment]
On behalf of the Rules Committee:

The Rules Committee voted by e-mail 6-0 to close this issue. This means we've examined the discussion and decided that nothing ought to be changed at this time.

@scottpeterson please feel free to open up another issue if you remember what you wanted to propose here!

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md
