### ISSUE TITLE
Add cover pages to (some) build output

### ISSUE THREAD

**Issue by gryphonshafer** [gryphonshafer/Quizzing-Rule-Book#48]
For PDF build output and *maybe* HTML build output, add a cover page with:

- logo
- web site links
- revision date

Investigate adding table of contents and page numbers.

**Comment by zctinker** [comment]
Are you able to link to an image and embed it to a blank page? If so then we could just add the cover page that way. 
https://riverwoodalliance.sharepoint.com/:f:/s/BibleQuizzing/EsrzmN7aY_dMqIsppDBRDhgBnzlf0_e7irjIQJHDzakaKQ?e=RBCADU

**Comment by gryphonshafer** [comment]
I can't seem to get any browser or PDF generator to automatically generate page numbers. However, just about every browser supports manual page numbers if you load the HTML and print with page numbers option enabled.
