### ISSUE TITLE
Draft wording/definition for Rule Book Examples

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/Quizzing-Rule-Book#53]
Examples are a representation of a rule, a tangible illustration of a rule. Since rules are often stated using abstract wording and concepts, and often in generalized forms, it can be hard to visualize the rule's application without an example. 

That said, each example is just one representation. It does not aim to exemplify every possible application of the rule. As such, if the example appears to only cover part of the rule, you're probably right! The fact that the lone example covers only part of the rule should not be interpreted as implying that the rule is actually different than stated. The correct interpretation should be that the example(s) do not fully cover every application of the rule. 

In older versions of the rulebook, where the rulebook was confusingly written, poorly written, or inconsistently written, any examples were heavily scrutinized to gain any insights into how to clarify the rule. This was never intended. It is not intended now. If anyone feels that the rulebook rules can be written better, they should ask questions and/or submit a Pull Request, so that the wording can be improved.

**Comment by gryphonshafer** [comment]
Resolved with 4368db2, which will be pushed... eventually...
