### ISSUE TITLE
Program Idea that pulls out cool material & question set findings

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/Quizzing-Rule-Book#61]
* look at material text, finds repeated multi-word (>=3 words) phrases that are the same or almost the same (like 1 or maybe 2 words different). Lists them out with the most common and most longest and most the same highest.
* Find "context unique words/phrases."  These are interesting for studying and jumping strategy, since to the quizzer they are in essence purely unique. This has zero impact on question writers and QMs.
* Search for "occurrence rich contexts", (e.g. "John the Baptist" appears 4x in a single context.
* Generate stats from a given question set for "most/least common first words of the question, by type", can also calculate for "first n words in the question"
* Generate stats on the most unique word rich verses, chapters, books, contexts, etc.

**Comment by gryphonshafer** [comment]
This isn't really a rule book thing, though. However, I do like it. A lot.
