### ISSUE TITLE
Max Points Deducted

### ISSUE THREAD

**Issue by zctinker** [gryphonshafer/Quizzing-Rule-Book#63]
Change the wording from:

No more than -10 points can be deducted per question asked due to an error

to

No more than 10 points can be deducted per question asked due to an error
or
No more than -10 points can be assigned per question asked due to an error

Original Wording
> Never will more than 10 points be deducted from the team score for a single infraction
> (error, foul, or overruled challenge).

**Comment by scottpeterson** [comment]
Ah, a fun double negative.  I'm in favor of `No more than 10 points can be deducted per question asked due to an error`

**Comment by gryphonshafer** [comment]
This ticket is somewhat related to #78.

**Comment by scottpeterson** [comment]
This should technically be fixed as well. 
<img width="486" alt="Screen Shot 2021-03-16 at 10 44 52 PM" src="https://user-images.githubusercontent.com/13351944/111406779-44fda280-86a9-11eb-9a22-ae01fe3c68e7.png">

**Comment by jswingle** [comment]
Scott's "no more than 10 points" is ideal IMO.
