### ISSUE TITLE
"Romans, James" out of order

### ISSUE THREAD

**Issue by gryphonshafer** [gryphonshafer/Quizzing-Rule-Book#67]
Traditionally, in the "Romans, James" season, we memorize James first, which is out of Biblical book order. We may want to change the material scope reference to list James first. Or maybe make some sort of note about that after the table.

**Comment by Philip-Osterlund** [comment]
That's interesting.  In our district (NCD) we have studied Romans first, then James.

**Comment by JoshJetto** [comment]
I think it actually makes more sense to do Romans first and then James, because Romans provides the theological basis for justification by faith alone, that is the Gospel of our salvation from which our actions as believers spring. James is addressing issues of false practice (i.e. that a person can be saved by a faith in Christ that is of such a nature that it does not result in changed living). Students memorizing James first may become confused and think that they are saved by some combination of works and faith. It would make more sense, I think, for them to get the foundation in Romans (and its practical outworking in Romans 12-16) and then build on that further by learning James.

**Comment by kclimenhaga** [comment]
We have also generally memorized Romans first. Our reasoning has always been more practical than theological, but I'm interested to see Josh's theological support for this order.

**Comment by jttower** [comment]
WGL also memorizes Romans first.  I think Josh's reasoning is well-stated and I agree.

**Comment by ZacharyTinker** [comment]
Great Lakes has always memorized James first as well. We do this for several reasons, though on a more practical level.

1) James is shorter. Being able to have the first quiz meet cover a complete book has been a huge "win" for our district. It allows rookie quizzers to start the year off with a fuller understanding of how full context can change how you study and quiz. 

2) James is an "easier" book to understand. Paul's writing can be difficult to understand for a lot of people, but especially for young quizzers. e.g. I do not do what I want to do, but I do..... Starting with the "easier" book has been less intimidating for our quizzers both rookie and veteran and we see great levels of engagement, that carries through the rest of the year longer. 



**But.... All that being said, each district can choose any order to memorize any of the multi-book years. All of the resources are released at the beginning of the season making it a possibility for a district to reorder the books however they want.**

**Comment by jswingle** [comment]
I love the discussion about it (I'm on #TeamJamesFirst by the way) but I don't think the rulebook needs to change. It has to be ordered in _some_ way, but districts are always free to do things like this their own way, and we should encourage that mentality.

**Comment by jttower** [comment]
On behalf of the Rules Committee:

On 03/26/2022, the Rules Committee voted 6-0 to close this issue. This means we've examined the discussion and decided that nothing ought to be changed at this time.

The books in the rule book are ordered as they appear in the Bible, and there is no reason to change this.  Districts are free to order the year's material however they deem best for their circumstances, but this doesn't need to be spelled out in the rule book. 

Please note that the closing of an issue doesn't mean the issue cannot be raised again in the future.

For more information on the rulebook Change Management Process, please visit: https://github.com/gryphonshafer/Quizzing-Rule-Book/blob/master/content/rule_book/change_management.md
