### ISSUE TITLE
"Push-button quizzing" better as "alternative jumping methods"

### ISSUE THREAD

**Issue by gryphonshafer** [gryphonshafer/Quizzing-Rule-Book#68]
Feedback from a reviewer:

> Does push button jumping include foot jumping for physically disabled quizzers? Would alternate jumping methods be a better way to word it? then would you need to define those methods?

The only place where push-button quizzing is mentioned is the last bullet under section 3.5, and it's a pretty vague reference. I agree with you that "alternative jumping methods" is better, and we should define those.

**Comment by scottpeterson** [comment]
Agreed.

**Comment by ARMediting** [comment]
The Rules Committee discussed this issue on April 10, 2022.
The vote was 6-0 to change the wording in question to "Alternative jumping methods can be provided if needed by physically disabled quizzers."
This now moves to a pull request.
