### ISSUE TITLE
Coach may confer with an err-out quizzer

### ISSUE THREAD

**Issue by gryphonshafer** [gryphonshafer/Quizzing-Rule-Book#69]
Under the protests section, there's a line:

> The coach may only confer with their assistant coach and substitute quizzer, before protesting.

Ignoring the grammatical error, this phrase doesn't consider the pretty common case of a quizzer in a 4-person team that errs-out. Technically, they would not have been subbed-out and are not a substitute quizzer, and so technically, they can't be consulted with. However, I think there'd be near if not complete unanimity that such a quizzer could be consulted.

**Comment by scottpeterson** [comment]
I would consider this a current rule book bug. Replacing "substitute quizzer" with something like "any quizzer members of the team not currently seated on the stage / in the quiz" would meet functional parity, IMO.

**Comment by scottpeterson** [comment]
also "substitute quizzer" is not defined in the current rule book. I wouldn't think that "being subbed in/out in this current quiz" is required to be considered a "substitute quizzer." I would think "team member not currently in the quiz" is a reasonable definition.

**Comment by gryphonshafer** [comment]
I'm moving this ticket into the v1 Review Edits milestone because I agree with Scott that this is a v1 bug.

**Comment by jswingle** [comment]
v1 bug IMO, based purely on my intuition that nobody is even aware of it except us. In practice, I wouldn't imagine any official saying an erred-out quizzer can't consult.
