### ISSUE TITLE
Recording Device Policy

### ISSUE THREAD

**Issue by scottpeterson** [gryphonshafer/Quizzing-Rule-Book#71]
For a given quiz meet, for fairness, either all quiz rooms should have a recording device, or none should.

**Comment by jswingle** [comment]
Agreed, and I would add that at Internationals it should be considered standard practice and essential.

**Comment by jswingle** [comment]
@scottpeterson What do you think about writing a rule more generic than this one? Something along the lines of, in general all the quiz rooms at a meet need to have the same features/amenities, within reason.

This quickly becomes logistically tricky. I remember an Internationals where we only had pads in 2 of the rooms, but benches in another 2 rooms. We had practiced on benches, and were terrible at the pads, and a lot of our prelims ended up being in the rooms with pads. This was frustrating, but of course, benches aren't cheap, either to purchase OR to transport.

**Comment by scottpeterson** [comment]
I intended this to be specific to recording devices.  I think it makes total sense, if it's not logistically possible for all rooms to have them, for no rooms to have them. 

When it comes to jump equipment, while I would prefer that, if all rooms cannot have benches, that no room should have benches, I feel less strongly about that. 

This rule is a bit tough. It comes from a lot of discussion about the fairness of recording devices vs not (and all the nuance over "QM didn't hear them even though everyone else did", etc)---so I don't want to punt and say "meet director can decide" because it's unlikely a meet director would have the history, experience, and backstory to make the best decision. 

But it's also not a big deal.

**Comment by jswingle** [comment]
I'm 100% in favor of a recording device consistency rule, but I also think it wouldn't be egregious if, say, a quiz meet didn't use any recording devices at all until finals. That would technically be a violation of the rule you're proposing but I wouldn't mind.

My bigger concern would be that all rooms which are _serving the same bracket of quizzing_ are consistent, such that there isn't a lack of consistency based on draw. If 4 rooms are doing prelims, all 4 rooms should use recording equipment during the entirety of prelims, or none of them should.

**Comment by scottpeterson** [comment]
oh completely agreed. Once you're down to 1-2 rooms, whatever those rooms do to be consistent with each other, is fair to participants.    And I only consider this level of detail to be really necessary at Internationals.

**Comment by ARMediting** [comment]
Since the rules technically only apply to Internationals, does this need stated? Or should it go in a "best practices" section?

**Comment by scottpeterson** [comment]
I'm a fan of "the whole rule book" and "Internationals specific overrides" and I'd put this in the overrides.

**Comment by jswingle** [comment]
+1 to being in the IBQ-specific rules, but I noticed we already have a clause to that effect. Under 7.6 "Equipment":

"An audio recording system must be used in all rooms."

@scottpeterson Do you want to amend this rule or keep it as it is? The only amendment I think we would have to make is specifying that if no rooms are using audio recording, all the others have to stop as well. But TBH I think this rule is better and a little stronger.

**Comment by scottpeterson** [comment]
I would be in favor of such an amendment.

**Comment by jswingle** [comment]
Language change proposal under 7.6:

"An audio recording system _should be used_. To maintain fairness and consistency across quiz rooms, either all quiz rooms must use such equipment, or none can use it."

Here's a proposal for how to phrase it, though ultimately I don't think this is much of an improvement over the current rule. What say ye, @scottpeterson ?

**Comment by ARMediting** [comment]
I'd say the rule states it how we all agree it should be for Internationals. And it sounds from other issues like our shared sentiment is that the rulebook should deal only in Internationals rules. Therefore I propose closing out this issue with no changes.
