### ISSUE TITLE
Finish Clarifications in Version 3dcc7f8, dated 2021-03-04 18:20:11 GMT

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#74]
Section 1.2.2.4.3 Finish, sentence 2
Current reading:
  These 1st 5 words must be unique to all finish questions of the exact same type: for example, FTV compared to all FTVs, FT to all FTs, F2V to all F2Vs, FTN to all FTNs.

Suggested Modification:
  These 1st 5 words must be unique to all possible finish questions of the exact same type: for example, FTV compared to all possible FTVs, FT to all possible FTs, F2V to all possible F2Vs, FTN to all possible FTNs.

Reason for clarification: Not all possible FTVs are likely to be included in the list of all FTVs in the question list, yet the quizzer should have no access to the complete question list.  Therefor, in the example of FTVs, if two verses start with the same 5 words, those two verses are not permitted to be FTVs.  With the current reading, one of those verses could be considered for an FTV, as long as the other is not included in the full question list.  Similarly, with FT, F2V and FTN.

**Comment by gryphonshafer** [comment]
I agree. And I also think the way it currently reads is technically a bug, though minor. We care about the possible Fs, not what are the actual Fs. I'm in favor of considering a fix to this in v1, but I'd like other members of the committee to weigh in.

**Comment by jswingle** [comment]
This clears up the intent of the rule nicely. 100% should incorporate

**Comment by scottpeterson** [comment]
I like the edit but wouldn't consider it FE. The current rulebook makes no distinction between "possible" and "written" questions. 

Though everyone interprets and applies it as "possible" so perhaps making it clearer IS FE.

**Comment by zctinker** [comment]
I will also say that I agree and like how it clarifies. I agree that it reads as a rule book bug.

**Comment by jswingle** [comment]
Re:Scott's comments, I would definitely argue this is FE because "everyone" does in fact interpret and apply this the exact same way... thus, _functionally_ we are changing nothing about quizzing by making the rule more clearly reflect what everyone practices.
