### ISSUE TITLE
Suggested added definition: "Question Answer Duration Period"

### ISSUE THREAD

**Issue by ghost** [gryphonshafer/Quizzing-Rule-Book#75]
On my first read through the rule-book (Version 3dcc7f8, dated 2021-03-04 18:20:11 GMT), the term "question answer duration period" seemed a bit clumsy, until I realized what it was.  (Three adjectives modifying a noun, all three of which are nouns.)  Suggested definition:

**Question Answer Duration Period**
   The period of time allotted for a quizzer to answer a question, starting when the quiz-master gives the quizzer an opportunity to start answering the question, with a duration of 30 seconds

This definition could be included in the start of section 3. Quiz Process, although the first occurrence is in the last sentence of section 2.2.1.

**Comment by gryphonshafer** [comment]
I agree. I think this adds clarity. It certainly doesn't change anything related to functional equivalence, but it's not exactly an error as-is. I'm cool with addressing this change in v1, but I'm also OK with deferring this until after ratification. I'm placing this issue into the "v1 Review Edits" milestone for now, but I'd like to hear what the other committee members think.

**Comment by scottpeterson** [comment]
I think this current language is sufficient? `Prior to a quizzer's answer being correct or incorrect, quizzers may have up to 30 seconds to provide their answer`

**Comment by scottpeterson** [comment]
Perhaps adding back in that the QM recognizing the quizzer is what starts the 30-sec. This part of the rewritten rule book heavily implies that, but explicitly stating it is better `Everything the quizzer says while answering a question after being recognized by the quizmaster until their question answer duration period has elapsed or being called correct or incorrect`

**Comment by gryphonshafer** [comment]
Agreed. I'm in favor of adding back the `Everything` quote Scott wrote, but I'm also in favor of deferring this until after ratification.

**Comment by scottpeterson** [comment]
no, my "everything" quote exists already in the rewritten rule book.  I was saying it heavily implies what the beginning of the 30-seconds are, but isn't totally explicit about it. 

The 2018 rule book was "barely" more explicit. `A quizzer has 30 seconds to complete their answer after being recognized.`

**Comment by zctinker** [comment]
I like the clarity it adds, though I would say that nothing is "broken" at the moment without it. I think there is clarity to be added at some point, though that may be better suited for v2, but if it were to be added in v1 I would not argue.

**Comment by jswingle** [comment]
I think it is better suited for v2 personally. I don't think this is so fundamentally broken that it's begging for a v1 fix.

**Comment by gryphonshafer** [comment]
OK, let's defer this for v2.

**Comment by ARMediting** [comment]
Can't we just format 4.1. as a definition and replace all instances of "question answer duration period" with "answering period"?

**Comment by jswingle** [comment]
Looks like this one didn't get closed on 4/28 so closing it now.
