### ISSUE TITLE
Minor typos for 1.2.2.3.2 "once" not "twice"

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#77]
Paragraph 1, last sentence:
Current reading: "... occurs more than twice in the same chapter, necessitating a CVR question."
Revised reading: "... occurs more than once in the same chapter, necessitating a CVR question."

**Comment by gryphonshafer** [comment]
Agreed. This seems to me to be a bug should therefore be patched in v1.

**Comment by scottpeterson** [comment]
Yep.

**Comment by zctinker** [comment]
Agreed

**Comment by jswingle** [comment]
v1 fix for sure.
