### ISSUE TITLE
Diety Rule - Choice of Word

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#81]
Section 4.2.2 Deity Rule
I propose using the word "Trinity", rather than "Deity".

The word "Trinity" refers specifically to God the Father, God the Son, and God the Holy Spirit.
The word "deity" is generic, and refers to any  god, such as Zeus or Poseidon.
"The Deity" refers to God, the Supreme Being.

This terminology has bothered me since I started working with quizzing in 2007.  I've wondered if it was some sort of strange C&MA use of the word.

**Comment by scottpeterson** [comment]
Good thing to table for v1

**Comment by zctinker** [comment]
Agreed. This makes much more sense. Nothing C&MA related, my guess is that original writers just didn't think about lowercase "deities"

**Comment by scottpeterson** [comment]
changing "deity" to "trinity" is definitely not FE. But if we assume that the original writers intended "Trinity" then it's not. But I still think this is best for v2.

**Comment by zctinker** [comment]
Agreed, v2 makes the most sense.

**Comment by scottpeterson** [comment]
I simultaneously don't care much about the Deity Rule, but also think ~80% of it can be removed. You really only need 1 sentence of commentary explaining how certain names of the Trinity are ambiguous, and as such can't get a quizzer called incorrect.

**Comment by scottpeterson** [comment]
The Special Names bit is unnecessary. If we refer to "Demetrius the silversmith" we need all of that and not merely "Demetrius."  Dealing with the Trinity doesn't change that. There's nothing new introduced.

**Comment by gryphonshafer** [comment]
Theologically, "deity" is OK since as Christians there is only 1 deity, which is the Trinity. But I'm also OK changing the name to the Trinity rule. This is a good discussion item for v2.

**Comment by jswingle** [comment]
Closing this issue out, as the RC has already voted on this exact topic in another issue: https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/130
