### ISSUE TITLE
Section 4.5 Fouls - Minor type

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#82]
Sentence 1 reads: "... conduct that breaks the text of spirit of the rules."
This should read: "... conduct that breaks the text or spirit of the rules."

**Comment by scottpeterson** [comment]
Agreed.

**Comment by zctinker** [comment]
agreed

**Comment by gryphonshafer** [comment]
Agreed. I'll fix for v1.

**Comment by jswingle** [comment]
v1 fix for sure
