### ISSUE TITLE
4.6 Timeouts: Clarification

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#83]
The first two sentences read:
"Each team is allowed 2 1-minute timeouts. Only 1 of those timeouts may be taken after question number 17, including any alphanumeric question numbers."

I believe this indicates that each team is permitted 1 timeout after question 17, but perhaps this needs to be specifically stated for clarity.

**Comment by scottpeterson** [comment]
Seems clear to me already.

**Comment by zctinker** [comment]
This reads clear to me as well. Though I can see the interpretation of "there can be only 1 timeout after 17." the word "those" is slightly ambiguous.

We could change it to this at some point down the road.
`Each team is allowed 2 1-minute timeouts. Each team may only use 1 of those timeouts may be taken after question number 17, including any alphanumeric question numbers.`

**Comment by gryphonshafer** [comment]
Yeah, I'm thinking it's clear as is, but I'll leave this ticket open for v2 triage, in case the committee wants to consider adding some commentary or something.

**Comment by jttower** [comment]
I think this is clear as worded.

**Comment by ARMediting** [comment]
The Rules Committee discussed this on 4/10/2022. The vote was 6-0 to close the issue with no changes to the rulebook text, as we believe the wording is clear enough as is.
