### ISSUE TITLE
5.2 Logic - syntax error

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#84]
I don't program in ES, but I believe this is a syntax error.

After the line 'Set the scoresheet to "E".'
Current reading:
  If the current question form is "Standard" the quiz type begins with "3", then
Proposed reading:
  If the current question form is "Standard" **and** the quiz type begins with "3", then

**Comment by gryphonshafer** [comment]
Yes, this is an ES bug. Good catch. I say it needs to be fixed in v1.
