### ISSUE TITLE
6.1.1 Team Point Calculation - Clarification is needed.

### ISSUE THREAD

**Issue by ghost** [gryphonshafer/Quizzing-Rule-Book#86]
The first line of paragraph 2 reads:
   "A team will be awarded a minimum of team points based on their placement:"
Suggested rephrasing:
   "After applying the placement adjustment in calculating team points, further apply the following minima, based on placement:"

(This is clunky English.  Perhaps better phrasing is available.)

Note: This algorithm is how I think of the team points, rather than the algorithm in the 2018 rule-book.  However, the 2018 description is perhaps more succinct.

**Comment by scottpeterson** [comment]
I think the rewrite is wildly more clear. I always thought it was confusing to co-mingle placement adjustments with minimums in the same breath.

**Comment by kclimenhaga** [comment]
I like the idea, but it is kind of confusing wording. Would this be better?
"Each team will receive either the adjusted points total, or the following, whichever is greater:"

**Comment by ARMediting** [comment]
I like Kristen's wording, but there still feels like there should be a better way to introduce the two at the top of the section. Maybe just adding a "However" to Kristen's sentence would do it.

**Comment by jttower** [comment]
I propose putting the team score calculation together with the minimum. This is how I always think about it. I also think the first sentence needs a little tweak. 
_Current:_
6.1.1. Team Points Calculation

Team points are calculated by dividing the team score immediately after question 20 by 10 and then applying placement adjustment:

    No change for 1st
    -1 points for 2nd
    -2 points for 3rd

A team will be awarded a minimum of team points based on their placement:

    10 for 1st
    5 for 2nd
    1 for 3rd


_Proposed:_
6.1.1. Team Points Calculation

Team points are calculated by dividing the team score immediately after question 20 **(including any A and B questions)** by 10 and then applying placement adjustment:

    No change for 1st, **(minimum of 10 points)**
    -1 points for 2nd, **(minimum of 5 points)**
    -2 points for 3rd, **(minimum of 1 point)**
(Then delete the last section.)

**Comment by jswingle** [comment]
I created a pull request for this on Apr. 16 but neglected to close out the issue properly and indicate that there was a 6-0 vote in favor of @jttower 's proposal.
