### ISSUE TITLE
Sections 6.2.1.2 and 6.1.2.3 Turnament Brackets "B" and "C", Clarification

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#87]
These two sections have the phrase "(if needed)" prior to describing what "(if needed)" means.

Option 1:  Adjust these (or the first occurrence in each section) to "(if needed, as described below)"
Option 2:  Give precisely when these quizzes are needed:
   (if needed, when no team has taken 1st twice)

**Comment by scottpeterson** [comment]
I think this is just a port over. If we think it's a bug we can fix.

**Comment by zctinker** [comment]
Agreed, if it's a bug then let's fix it.

**Comment by gryphonshafer** [comment]
I agree. I think it's a bug. I'll fix it.
