### ISSUE TITLE
6.2.3 Tournamen Bracket "C", Quiz D typo

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#89]
In section 6.2.1.3. Tournament Bracket "C", Bracket Design, bullets 4 and 5 read,
- Quiz D: 1st Quiz A, 1st Quiz B, **2nd** Quiz C  
- Quiz E: 2nd Quiz A, 2nd Quiz B, **2nd** Quiz C

I believe bullet 4 should read,
- Quiz D: 1st Quiz A, 1st Quiz B, **1st** Quiz C

**Comment by scottpeterson** [comment]
yep, bug in 2018 rule book. Should patch.

**Comment by zctinker** [comment]
Agreed.

**Comment by gryphonshafer** [comment]
Agreed. Will fix.
