### ISSUE TITLE
7.3 Event Registration - minor typo

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#90]
The 2nd to last sentence of paragraph 2 reads:
   District participation fees the current quiz season...
This should read:
   District participation fees **for** the current quiz season...

**Comment by scottpeterson** [comment]
agreed.

**Comment by zctinker** [comment]
agreed.

**Comment by gryphonshafer** [comment]
Agreed. Will fix.
