### ISSUE TITLE
7.4.2. Statistician  - Clarification

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#91]
Bullet 1 states, "Statistician shall: Not be a regular scorekeeper"

1st: A grammar error in agreement in number.
2nd: I assume this means that the statistician for an event is not also a regular score-keeper for that event.

Note: Lately in my district, I have been a quiz-master for a number of quiz meets, and after the meet is over I am the primary statistician.  A number of people wear multiple hats.

**Comment by scottpeterson** [comment]
This is specifically for Internationals so I think it's inclusion is good. That meet should take pains to ensure officials/administrators aren't wearing multiple (too many) hats.

I would agree with your comments if this wasn't Internationals-specific.

**Comment by zctinker** [comment]
I agree with Scott, at the IBQ level multiple hats should be avoided as best as possible, at district level it's all but necessary.

**Comment by gryphonshafer** [comment]
I'll fix the grammar error for v1.

**Comment by jswingle** [comment]
Agreed with Scott.
