### ISSUE TITLE
Request for removal of the Unique Word rule

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#94]
Josh Jetto has again requested removing the Unique Word rule.
(Please reference the request Josh Jetto previously submitted.)

**Comment by jswingle** [comment]
Closed on behalf of the Rules Committee, as mentioned in the original posting this is an identical issue to this one linked:
https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/109
