### ISSUE TITLE
Section 2.1.1 - Simplify statement

### ISSUE THREAD

**Issue by Philip-Osterlund** [gryphonshafer/Quizzing-Rule-Book#96]
Current reading:
   Scorekeepers must be notified which quizzer is the captain and which is co-captain before the quizzers take their seats to begin the quiz.

Suggested reading:
   Scorekeepers must be notified which quizzer is the captain and which is co-captain before the quiz begins.

(If the quizzers happen to sit down before the coach has informed the scorekeeper of the captain and co-captain, it seems odd that the quizzers would have to stand up again...)

**Comment by jttower** [comment]
I agree with the suggested change.

**Comment by jswingle** [comment]
Yeah, the current reading is more specific than it needs to be. The C/CC just need to be known before question 1 hits, it's not an issue if the SK needs to remind a coach during light testing or a practice question or whatever.

**Comment by jttower** [comment]
Rules Committee voted 3/20/22 to change to:
"Scorekeepers must be notified which quizzer is the captain and which is co-captain before the quiz begins."
Vote passed 6-0.
On behalf of the Rules Committee, this issue is closed.
