### ISSUE TITLE
Section 2.2.1.1.2. Reference Questions Request

### ISSUE THREAD

**Issue by ghost** [gryphonshafer/Quizzing-Rule-Book#97]
Request from NCD DQLT:

Remove requirement to provide the question if the text of the question is started (i.e. if beyond the reference).

- Quizzer should not have to give the question at that point (i.e. CR and CVR types have this INT aspect and we don’t ask for this for an INT type question). 

- Where the quizzer has provided the answer, providing the question does not help them know the text better.

- This often confuses quizzers and even coaches; plus given at IBQ the Quiz Master is not likely to get past the reference anyway this rule wouldn’t seem to serve IBQ either.

**Comment by jttower** [comment]
I think this is a repeat of pull request #106 which has further explanation.  This request can probably be closed and merged with that one.

**Comment by jswingle** [comment]
Agreed. @josiah-leinbach I'll let you make the call on whether to close and merge since you're assigned to this one. When I do this I've just been linking to the closed issue in a comment on the open issue.

**Comment by jswingle** [comment]
Closing this issue, #106 is identical.
