### ISSUE TITLE
Section 3.4 Clarification

### ISSUE THREAD

**Issue by ghost** [gryphonshafer/Quizzing-Rule-Book#98]
Suggestion: Add Narrative/Epistle to Minimum and Maximum columns in the Question Type Distribution table.  This is referenced ahead of the table but would be more clear if included in column headings.

(Personally, for clarity, I consider the table a great improvement over the 2018 rule-book.)

**Comment by ARMediting** [comment]
I'm a bit confused exactly where this would be included in the table. Is there a way to see a preview of it? Also, I think it would be even clearer to add two extra columns or rearrange the columns there, so  they're grouped as min/max for narrative, and min/max for epistle.

**Comment by gryphonshafer** [comment]
The following are a couple of options I derived based on the proposal.

Honestly, I don't think this adds any clarity over the current table; it clutters the table, decreasing the table's usefulness. Anyone who reads the sentence immediately prior to the table should understand the display convention, and anyone who doesn't read and therefore doesn't understand lacks my sympathies. 

## (Current) Question Type Distribution

In the below table, any minimum or maximum variation between material seasons is indicated in a `Narrative/Epistle` format.

| Type Group      | Minimum | Maximum | Question Types       |
|-----------------|--------:|--------:|----------------------|
| Interrogative   |     8/9 |   14/16 | INT                  |
| Multiple Answer |       1 |       2 | MA                   |
| Reference       |       3 |     6/7 | CR, CVR, MACR, MACVR |
| Quote           |     2/3 |     3/4 | Q, Q2V               |
| Finish          |       3 |       4 | FT, FTN, FTV, F2V    |
| Situation       |     2/0 |     4/0 | SIT                  |

## (Option "A") Question Type Distribution

In the below table, any minimum or maximum variation between material seasons is indicated in a `Narrative/Epistle` format.

| Type Group      | Minimum *(Narrative/Epistle)* | Maximum *(Narrative/Epistle)* | Question Types       |
|-----------------|------------------------------:|------------------------------:|----------------------|
| Interrogative   |                           8/9 |                         14/16 | INT                  |
| Multiple Answer |                             1 |                             2 | MA                   |
| Reference       |                             3 |                           6/7 | CR, CVR, MACR, MACVR |
| Quote           |                           2/3 |                           3/4 | Q, Q2V               |
| Finish          |                             3 |                             4 | FT, FTN, FTV, F2V    |
| Situation       |                           2/0 |                           4/0 | SIT                  |


## (Option "B") Question Type Distribution

In the below table, any minimum or maximum variation between material seasons is indicated in a `Narrative/Epistle` format.

| Type Group      | Minimum                   | Maximum                     | Question Types       |
|-----------------|--------------------------:|----------------------------:|----------------------|
| Interrogative   | 8/9 *(Narrative/Epistle)* | 14/16 *(Narrative/Epistle)* | INT                  |
| Multiple Answer |   1 *(Narrative/Epistle)* |     2 *(Narrative/Epistle)* | MA                   |
| Reference       |   3 *(Narrative/Epistle)* |   6/7 *(Narrative/Epistle)* | CR, CVR, MACR, MACVR |
| Quote           | 2/3 *(Narrative/Epistle)* |   3/4 *(Narrative/Epistle)* | Q, Q2V               |
| Finish          |   3 *(Narrative/Epistle)* |     4 *(Narrative/Epistle)* | FT, FTN, FTV, F2V    |
| Situation       | 2/0 *(Narrative/Epistle)* |   4/0 *(Narrative/Epistle)* | SIT                  |

**Comment by gryphonshafer** [comment]
For completeness, here's another example option. This seems less worse than A or B, but I still think the Current table is cleaner, clearer, and therefore easier to reference at a glance.

## (Proposed "C") Question Type Distribution

In the below table, any minimum or maximum variation between material seasons is indicated in a `Narrative/Epistle` format.

| Type Group      | Minimum Narrative | Minimum Epistle | Maximum Narrative | Maximum Epistle | Question Types       |
|-----------------|------------------:|----------------:|------------------:|----------------:|----------------------|
| Interrogative   |                 8 |               9 |                14 |              16 | INT                  |
| Multiple Answer |                 1 |               1 |                 2 |               2 | MA                   |
| Reference       |                 3 |               3 |                 6 |               7 | CR, CVR, MACR, MACVR |
| Quote           |                 2 |               3 |                 3 |               4 | Q, Q2V               |
| Finish          |                 3 |               3 |                 4 |               4 | FT, FTN, FTV, F2V    |
| Situation       |                 2 |               0 |                 4 |               0 | SIT                  |

**Comment by jswingle** [comment]
I agree with Gryphon that it's clear as is. No need to clutter the table, and anyone confused by the "x/y" format should be naturally looking for a nearby explanation.

**Comment by Philip-Osterlund** [comment]
Please remove Phil's email from your list.  He passed away in March.

Thank you, Helen Osterlund

**Comment by JoshJetto** [comment]
Gryphon, are you able to remove Philip Osterlund from the rulebook group/notifications so that his widow doesn't keep getting notifications in his email account? If not, how would she go about removing him from the various rulebook issues he opened or commented on?

**Comment by scottpeterson** [comment]
https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions

**Comment by gryphonshafer** [comment]
@JoshJetto My understanding is there's not a way I can remove Philip's account from GitHub notifications. It's something the recipient/accessor of the emails needs to manage. They can click on the "unsubscribe" link in any GitHub email, or use any of the methods described in [@scottpeterson's comment](https://github.com/gryphonshafer/Quizzing-Rule-Book/issues/98#issuecomment-1163009523).

**Comment by josiah-leinbach** [comment]
The rules committee voted unanimously on 1 July 2022 to close Issue #98, having agreed that the current format is clear and that the proposed change would clutter the distribution table.
